# Generated by Django 6.0 on 2025-12-19 00:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('primary_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('chest', 'Chest'), ('front_delts', 'Front Delts'), ('side_delts', 'Side Delts'), ('triceps', 'Triceps'), ('lats', 'Lats'), ('upper_back', 'Upper Back'), ('rear_delts', 'Rear Delts'), ('biceps', 'Biceps'), ('forearms', 'Forearms'), ('abs', 'Abs'), ('obliques', 'Obliques'), ('lower_back', 'Lower Back'), ('quads', 'Quads'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('hip_flexors', 'Hip Flexors'), ('adductors', 'Adductors'), ('abductors', 'Abductors')], max_length=50), default=list)),
                ('secondary_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('chest', 'Chest'), ('front_delts', 'Front Delts'), ('side_delts', 'Side Delts'), ('triceps', 'Triceps'), ('lats', 'Lats'), ('upper_back', 'Upper Back'), ('rear_delts', 'Rear Delts'), ('biceps', 'Biceps'), ('forearms', 'Forearms'), ('abs', 'Abs'), ('obliques', 'Obliques'), ('lower_back', 'Lower Back'), ('quads', 'Quads'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('hip_flexors', 'Hip Flexors'), ('adductors', 'Adductors'), ('abductors', 'Abductors')], max_length=50), default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(choices=[('selectorized', 'Selectorized'), ('plate_loaded', 'Plate Loaded'), ('smith', 'Smith Machine')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
