# Generated by Django 6.0 on 2025-12-19 02:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrainingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_equipment_modalities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('free_weights', 'Free Weights'), ('machines', 'Machines'), ('cables', 'Cables'), ('bodyweight', 'Bodyweight'), ('bands_suspension', 'Bands / Suspension')], max_length=50), blank=True, default=list)),
                ('excluded_equipment_stations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('rack', 'Rack'), ('bench', 'Bench'), ('pull_up_bar', 'Pull-up Bar'), ('dip_station', 'Dip Station'), ('floor', 'Floor')], max_length=50), blank=True, default=list)),
                ('excluded_equipment_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('selectorized', 'Selectorized'), ('plate_loaded', 'Plate Loaded'), ('smith', 'Smith Machine')], max_length=50), blank=True, default=list)),
                ('excluded_exercise_attributes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('high_impact', 'High Impact'), ('overhead', 'Overhead'), ('spotter_advised', 'Spotter Advised'), ('technically_complex', 'Technically Complex'), ('floor_required', 'Floor Required'), ('high_joint_stress', 'High Joint Stress')], max_length=50), blank=True, default=list)),
                ('sessions_per_week', models.SmallIntegerField(default=3)),
                ('training_intensity', models.PositiveSmallIntegerField(default=5)),
                ('max_session_mins', models.IntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Training Preferences',
                'verbose_name_plural': 'User Training Preferences',
                'db_table': 'account_usertrainingpreferences',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_number', models.PositiveIntegerField()),
                ('focus', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('arms', 'Arms'), ('shoulders', 'Shoulders'), ('core', 'Core'), ('full_body', 'Full Body'), ('chest_triceps', 'Chest & Triceps'), ('back_biceps', 'Back & Biceps'), ('push', 'Push'), ('pull', 'Pull')], max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.exercise')),
                ('gym_equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_exercises', to='gym.gymequipment')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.workout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField()),
                ('target_weight_lbs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('target_reps', models.PositiveSmallIntegerField()),
                ('rest_seconds', models.PositiveSmallIntegerField(default=60)),
                ('actual_weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actual_reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.workoutexercise')),
            ],
            options={
                'ordering': ['set_number'],
                'unique_together': {('workout_exercise', 'set_number')},
            },
        ),
    ]
