# Generated by Django 6.0 on 2025-12-15 04:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrainingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_equipment_modalities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('free_weights', 'Free Weights'), ('machines', 'Machines'), ('cables', 'Cables'), ('bodyweight', 'Bodyweight'), ('bands_suspension', 'Bands / Suspension')], max_length=50), blank=True, default=list)),
                ('excluded_equipment_stations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('rack', 'Rack'), ('bench', 'Bench'), ('pull_up_bar', 'Pull-up Bar'), ('dip_station', 'Dip Station'), ('floor', 'Floor')], max_length=50), blank=True, default=list)),
                ('excluded_machine_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('selectorized', 'Selectorized'), ('plate_loaded', 'Plate Loaded'), ('smith', 'Smith Machine')], max_length=50), blank=True, default=list)),
                ('excluded_exercise_attributes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('high_impact', 'High Impact'), ('overhead', 'Overhead'), ('spotter_advised', 'Spotter Advised'), ('technically_complex', 'Technically Complex'), ('floor_required', 'Floor Required'), ('high_joint_stress', 'High Joint Stress')], max_length=50), blank=True, default=list)),
                ('sessions_per_week', models.SmallIntegerField(default=3)),
                ('training_intensity', models.PositiveSmallIntegerField(default=5)),
                ('max_session_mins', models.IntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Training Preferences',
                'verbose_name_plural': 'User Training Preferences',
                'db_table': 'account_usertrainingpreferences',
            },
        ),
    ]
