# Generated by Django 6.0 on 2025-12-19 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymequipment',
            options={'verbose_name_plural': 'Gym equipment'},
        ),
    ]
