from __future__ import annotations

from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField
from django.db import models

from training.enums import (
    EquipmentModality,
    EquipmentStation,
    EquipmentType,
    ExerciseAttribute,
    WorkoutFocus,
    WorkoutStatus,
)

User = get_user_model()


class UserTrainingPreferences(models.Model):
    """Training preferences for a user, using a blacklist model."""

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="training_preferences",
    )

    excluded_equipment_modalities = ArrayField(
        models.CharField(max_length=50, choices=EquipmentModality.choices),
        default=list,
        blank=True,
    )

    excluded_equipment_stations = ArrayField(
        models.CharField(max_length=50, choices=EquipmentStation.choices),
        default=list,
        blank=True,
    )

    excluded_equipment_types = ArrayField(
        models.CharField(max_length=50, choices=EquipmentType.choices),
        default=list,
        blank=True,
    )

    excluded_exercise_attributes = ArrayField(
        models.CharField(max_length=50, choices=ExerciseAttribute.choices),
        default=list,
        blank=True,
    )

    sessions_per_week = models.SmallIntegerField(default=3)
    training_intensity = models.PositiveSmallIntegerField(default=5)
    max_session_mins = models.IntegerField(default=60)

    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "account_usertrainingpreferences"
        verbose_name = "User Training Preferences"
        verbose_name_plural = "User Training Preferences"

    def __str__(self) -> str:
        return f"Training Preferences for {self.user.email}"


class Workout(models.Model):
    """A user's workout session."""

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="workouts")
    workout_number = models.PositiveIntegerField()
    focus = models.CharField(max_length=50, choices=WorkoutFocus.choices)
    status = models.CharField(
        max_length=20,
        choices=WorkoutStatus.choices,
        default=WorkoutStatus.SCHEDULED,
    )
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"Workout #{self.workout_number} - {self.user.email}"


class WorkoutExercise(models.Model):
    """An exercise within a workout, linked to a specific gym equipment."""

    workout = models.ForeignKey(
        Workout, on_delete=models.CASCADE, related_name="exercises"
    )
    exercise = models.ForeignKey("catalog.Exercise", on_delete=models.PROTECT)
    gym_equipment = models.ForeignKey(
        "gym.GymEquipment",
        on_delete=models.PROTECT,
        related_name="workout_exercises",
    )
    order = models.PositiveSmallIntegerField(default=0)

    class Meta:
        ordering = ["order"]

    def __str__(self) -> str:
        return f"{self.workout} - {self.exercise.name}"


class WorkoutSet(models.Model):
    """A single set within an exercise, with target and actual values."""

    workout_exercise = models.ForeignKey(
        WorkoutExercise,
        on_delete=models.CASCADE,
        related_name="sets",
    )
    set_number = models.PositiveSmallIntegerField()

    # Target values (generated by the system)
    target_weight_lbs = models.DecimalField(max_digits=6, decimal_places=2)
    target_reps = models.PositiveSmallIntegerField()
    rest_seconds = models.PositiveSmallIntegerField(default=60)

    # Actual values (logged by user)
    actual_weight_lbs = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True
    )
    actual_reps = models.PositiveSmallIntegerField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["set_number"]
        unique_together = ["workout_exercise", "set_number"]

    def __str__(self) -> str:
        return f"{self.workout_exercise} - Set {self.set_number}"
